### ISSUE TITLE
timeline with marks

### ISSUE THREAD

**Issue by NikoKrause** [raphink/moderntimeline#16]
I saw this (https://tex.stackexchange.com/questions/204964/how-to-show-off-tex-skills-with-a-tex-typeset-cv). Is there an option in moderntimeline to add marks as shown in this image?
![https://i.stack.imgur.com/XvYpM.png](https://i.stack.imgur.com/XvYpM.png)

**Comment by tristancollins** [comment]
I have the code to do that - I had intended to submit it as a PR but alas... I’d be happy to share if it could be incorporated into a PR.

**Comment by raphink** [comment]
@tristancollins I'd welcome a PR for that.

**Comment by tristancollins** [comment]
It's on my list. Sorry for the delay.

**Comment by Tesla1179** [comment]
Hello everybody. This timeline looks really nice. Where can i get the code for that.

**Comment by raphink** [comment]
@tristancollins do you still want to provide a PR for that?

**Comment by tristancollins** [comment]
I gave it a go - but the number of changes was large. Unless there is a way for me to fork from a version from a few years ago (if I can work out when that was), apply the changes and then merge? I'm no expert in git so would appreciate help in this if anyone is willing. Failing that I can share the source easily enough but that would be stuck at the old version.

**Comment by tristancollins** [comment]
@ao2 @Tesla1179 @raphink @NikoKrause I've finally added a brief working example here: https://github.com/tristancollins/TCmoderntimelineCV 

Let me know if it works for you. The issue I had was transferring all the changes back to the .dtx to submit a proper PR...

**Comment by ao2** [comment]
@tristancollins thanks, I am not sure either when I'll be able to take a proper look at the code, but it's good to know it's out there and working. :)

**Comment by raphink** [comment]
Sorry for the delay @tristancollins. The next step would be to fork this repository and modify the dtx to add your changes.

**Comment by raphink** [comment]
The marks were implemented in #18
